from . import employee_inherit
from . import job_inherit
from . import location_history
from . import work
from . import salary_advance_inherit
from . import installment_lines
from . import contract_inherit
from . import maintenance_inherit
from . import employee_transfer
from . import res_config_settings
from . import leave_inherit
from . import allocation
from . import safety
from . import payslip_employee_inherit
from . import payroll
from . import project_line
from . import work_line
from . import production_line
from . import payslip_line_inherit
from . import report_statment
from . import over_time
