# -*- coding: utf-8 -*-
{
    'name': "HR Edit",
    'author': "Heba&Meery",
    'version': '17.0',
    'depends': ['base', 'hr_maintenance', 'hr', 'hr_skills','report_xlsx', 'ohrms_salary_advance', 'hr_payroll'],
    'application': True,
    'data': [
        'security/ir.model.access.csv',
        'data/maintenance_category_data.xml',
        'data/time_off_type.xml',
        'data/position.xml',
        'data/cron_create_allocation.xml',
        'data/helper_rule.xml',
        'data/mason_rule.xml',
        'data/staff_rule_data.xml',
        'views/employee_view.xml',
        'views/salary_advance_views.xml',
        'views/contract_view.xml',
        'views/maintenance_view.xml',
        'views/location_history_view.xml',
        'views/employee_transfer.xml',
        'views/work_line_view.xml',
        'views/production_line.xml',
        'views/work_view.xml',
        'views/leave_inherit.xml',
        'views/allocation.xml',
        'views/project_line_view.xml',
        'views/saftey.xml',
        'views/res_conf_view.xml',
        'views/payslip_employee_view.xml',
        'views/employee_document_view.xml',
        'views/payslip_view.xml',
        'views/report_settlement.xml',
        'views/over_time.xml',
        'report/salary_report.xml',
        'report/payroll_report.xml',
        'report/summry_sheet.xml',
        'report/english_certificate.xml',
        'report/arabic_certificate.xml',
        'report/payroll_report.xml',
        'report/leave_report.xml',
        'report/equipment.xml',
        'report/helper_payslip.xml',
        'report/mason_payslip.xml',
        'report/transfer.xml',
        'report/payslip_report_xls.xml',
        'report/over_time.xml',


    ],
    'assets': {
        'web.assets_backend': [
            'hr_edit/static/src/css/**',

        ], },
}
